# Bns logic
login.do=execute|com.gamebox.action.LoginAction
logout.do=execute|com.gamebox.action.LogoutAction
register.do=execute|com.gamebox.action.RegisterAction


# view page
home.do=/WEB-INF/views/home.jsp
admin.do=/WEB-INF/views/admin.jsp


